# Generated by Django 5.2.3 on 2025-07-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['payment_status'], 'permissions': [('carcel_order', 'Can carcel order')]},
        ),
    ]
