# Generated by Django 5.2.3 on 2025-07-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['payment_status'], 'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
