# Generated by Django 5.2.3 on 2025-07-24 11:52

import django.core.validators
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitem_order_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='store/resume', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/images', validators=[store.validators.validate_file_size]),
        ),
    ]
