# Generated by Django 5.2.3 on 2025-07-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='taggeditem',
            options={'ordering': ['tag']},
        ),
    ]
